server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/autoflowx

logging:
  level:
    root: INFO
    org.springframework: INFO

jwt:
  secret: "zD6tF8Jh@97Lm!aXoPc3VrQ9Uz#KwEtB"
  expiration: 86400000 # 1 day in milliseconds
